In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from itertools import cycle, islice

# This line lets us plot on our ipython notebook
%matplotlib inline

In [2]:
#Load raw precint results data 2008
df_08 = pd.read_table("proj_data/2008 General Election Results.txt", sep=',', header=None, low_memory=False)

#preview first 5 records...
df_08.head()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,2008,G,1,10,1,0,1,1,USP,DEM,...,NaN,NaN,0,5,1,0010,0,19,33,91
1,2008,G,1,20,1,0,1,1,USP,DEM,...,NaN,NaN,0,10,1,0020,0,19,33,91
2,2008,G,1,30,1,0,1,1,USP,DEM,...,NaN,NaN,0,15,1,0030,0,19,33,193
3,2008,G,1,40,1,0,1,1,USP,DEM,...,NaN,NaN,0,20,1,0040,0,19,33,91
4,2008,G,1,50,1,0,1,1,USP,DEM,...,NaN,NaN,0,25,1,0050,0,19,33,193

In [3]:
list(df_08)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32]

In [4]:
# export to clean in excel
df_08.to_csv('raw_results08.csv')

In [5]:
# bring clean data back in
df_08clean = pd.read_table("proj_data/raw_results08_clean.csv", sep=',', low_memory=False)

#preview first 5 records...
df_08clean.head()

   year  countycode party   cand  votes  FIPS
0  2008           1   DEM  OBAMA    154     1
1  2008           1   DEM  OBAMA    167     1
2  2008           1   DEM  OBAMA     97     1
3  2008           1   DEM  OBAMA    360     1
4  2008           1   DEM  OBAMA    178     1

In [6]:
df_08clean.shape

(46550, 6)

In [7]:
df_08clean['votes'].dtype

dtype('int64')

In [8]:
df_08clean['FIPS'].dtype

dtype('int64')

In [9]:
#List unique values in the df_16['cand'] column
df_08clean.cand.unique()

array(['OBAMA', 'MCCAIN', 'NADER', 'BARR', 'WRITE-IN'], dtype=object)

In [10]:
## create new column that is number of voters for obama
# Create a new column called df_08clean.democrat where the value is the votes if df_08clean.cand equals 'OBAMA'
# and 0 if not.
df_08clean['democrat'] = df_08clean['votes'].where(df_08clean['cand']=='OBAMA', 0)
df_08clean

       year  countycode party      cand  votes  FIPS  democrat
0      2008           1   DEM     OBAMA    154     1       154
1      2008           1   DEM     OBAMA    167     1       167
2      2008           1   DEM     OBAMA     97     1        97
3      2008           1   DEM     OBAMA    360     1       360
4      2008           1   DEM     OBAMA    178     1       178
5      2008           1   DEM     OBAMA    333     1       333
6      2008           1   DEM     OBAMA    377     1       377
7      2008           1   DEM     OBAMA    453     1       453
8      2008           1   DEM     OBAMA    356     1       356
9      2008           1   DEM     OBAMA    547     1       547
10     2008           1   DEM     OBAMA    636     1       636
11     2008           1   DEM     OBAMA    426     1       426
12     2008           1   DEM     OBAMA    319     1       319
13     2008           1   DEM     OBAMA    536     1       536
14     2008           1   DEM     OBAMA    246     1       246
15     2008           1   DEM     OBAMA    284     1       284
16     2008           1   DEM     OBAMA    130     1       130
17     2008           1   DEM     OBAMA    441     1       441
18     2008           1   DEM     OBAMA    380     1       380
19     2008           1   DEM     OBAMA    175     1       175
20     2008           1   DEM     OBAMA    364     1       364
21     2008           1   DEM     OBAMA    540     1       540
22     2008           1   DEM     OBAMA    953     1       953
23     2008           1   DEM     OBAMA    478     1       478
24     2008           1   DEM     OBAMA    408     1       408
25     2008           1   DEM     OBAMA    382     1       382
26     2008           1   DEM     OBAMA    197     1       197
27     2008           1   DEM     OBAMA    305     1       305
28     2008           1   DEM     OBAMA    409     1       409
29     2008           1   DEM     OBAMA    253     1       253
...     ...         ...   ...       ...    ...   ...       ...
46520  2008          67   OTH  WRITE-IN      5   133         0
46521  2008          67   OTH  WRITE-IN      4   133         0
46522  2008          67   OTH  WRITE-IN      2   133         0
46523  2008          67   OTH  WRITE-IN      5   133         0
46524  2008          67   OTH  WRITE-IN      4   133         0
46525  2008          67   OTH  WRITE-IN      0   133         0
46526  2008          67   OTH  WRITE-IN      0   133         0
46527  2008          67   OTH  WRITE-IN      6   133         0
46528  2008          67   OTH  WRITE-IN      1   133         0
46529  2008          67   OTH  WRITE-IN      5   133         0
46530  2008          67   OTH  WRITE-IN      6   133         0
46531  2008          67   OTH  WRITE-IN      5   133         0
46532  2008          67   OTH  WRITE-IN      5   133         0
46533  2008          67   OTH  WRITE-IN      2   133         0
46534  2008          67   OTH  WRITE-IN      5   133         0
46535  2008          67   OTH  WRITE-IN      7   133         0
46536  2008          67   OTH  WRITE-IN     11   133         0
46537  2008          67   OTH  WRITE-IN      3   133         0
46538  2008          67   OTH  WRITE-IN      6   133         0
46539  2008          67   OTH  WRITE-IN      4   133         0
46540  2008          67   OTH  WRITE-IN      3   133         0
46541  2008          67   OTH  WRITE-IN      3   133         0
46542  2008          67   OTH  WRITE-IN      7   133         0
46543  2008          67   OTH  WRITE-IN      5   133         0
46544  2008          67   OTH  WRITE-IN      4   133         0
46545  2008          67   OTH  WRITE-IN      4   133         0
46546  2008          67   OTH  WRITE-IN      5   133         0
46547  2008          67   OTH  WRITE-IN      7   133         0
46548  2008          67   OTH  WRITE-IN      7   133         0
46549  2008          67   OTH  WRITE-IN      0   133         0

[46550 rows x 7 columns]

In [11]:
## create new column that is number of voters for mccain
# Create a new column called df_08clean.republican where the value is the votes if df_08clean.cand equals 'MCCAIN' or 
# and 0 if not.
df_08clean['republican'] = df_08clean['votes'].where(df_08clean['cand']=='MCCAIN', 0)
df_08clean

       year  countycode party      cand  votes  FIPS  democrat  republican
0      2008           1   DEM     OBAMA    154     1       154           0
1      2008           1   DEM     OBAMA    167     1       167           0
2      2008           1   DEM     OBAMA     97     1        97           0
3      2008           1   DEM     OBAMA    360     1       360           0
4      2008           1   DEM     OBAMA    178     1       178           0
5      2008           1   DEM     OBAMA    333     1       333           0
6      2008           1   DEM     OBAMA    377     1       377           0
7      2008           1   DEM     OBAMA    453     1       453           0
8      2008           1   DEM     OBAMA    356     1       356           0
9      2008           1   DEM     OBAMA    547     1       547           0
10     2008           1   DEM     OBAMA    636     1       636           0
11     2008           1   DEM     OBAMA    426     1       426           0
12     2008           1   DEM     OBAMA    319     1       319           0
13     2008           1   DEM     OBAMA    536     1       536           0
14     2008           1   DEM     OBAMA    246     1       246           0
15     2008           1   DEM     OBAMA    284     1       284           0
16     2008           1   DEM     OBAMA    130     1       130           0
17     2008           1   DEM     OBAMA    441     1       441           0
18     2008           1   DEM     OBAMA    380     1       380           0
19     2008           1   DEM     OBAMA    175     1       175           0
20     2008           1   DEM     OBAMA    364     1       364           0
21     2008           1   DEM     OBAMA    540     1       540           0
22     2008           1   DEM     OBAMA    953     1       953           0
23     2008           1   DEM     OBAMA    478     1       478           0
24     2008           1   DEM     OBAMA    408     1       408           0
25     2008           1   DEM     OBAMA    382     1       382           0
26     2008           1   DEM     OBAMA    197     1       197           0
27     2008           1   DEM     OBAMA    305     1       305           0
28     2008           1   DEM     OBAMA    409     1       409           0
29     2008           1   DEM     OBAMA    253     1       253           0
...     ...         ...   ...       ...    ...   ...       ...         ...
46520  2008          67   OTH  WRITE-IN      5   133         0           0
46521  2008          67   OTH  WRITE-IN      4   133         0           0
46522  2008          67   OTH  WRITE-IN      2   133         0           0
46523  2008          67   OTH  WRITE-IN      5   133         0           0
46524  2008          67   OTH  WRITE-IN      4   133         0           0
46525  2008          67   OTH  WRITE-IN      0   133         0           0
46526  2008          67   OTH  WRITE-IN      0   133         0           0
46527  2008          67   OTH  WRITE-IN      6   133         0           0
46528  2008          67   OTH  WRITE-IN      1   133         0           0
46529  2008          67   OTH  WRITE-IN      5   133         0           0
46530  2008          67   OTH  WRITE-IN      6   133         0           0
46531  2008          67   OTH  WRITE-IN      5   133         0           0
46532  2008          67   OTH  WRITE-IN      5   133         0           0
46533  2008          67   OTH  WRITE-IN      2   133         0           0
46534  2008          67   OTH  WRITE-IN      5   133         0           0
46535  2008          67   OTH  WRITE-IN      7   133         0           0
46536  2008          67   OTH  WRITE-IN     11   133         0           0
46537  2008          67   OTH  WRITE-IN      3   133         0           0
46538  2008          67   OTH  WRITE-IN      6   133         0           0
46539  2008          67   OTH  WRITE-IN      4   133         0           0
46540  2008          67   OTH  WRITE-IN      3   133         0           0
46541  2008          67   OTH  WRITE-IN      3   133         0           0
46542  2008          67   OTH  WRITE-IN      7   133         0           0
46543  2008          67   OTH  WRITE-IN      5   133         0           0
46544  2008          67   OTH  WRITE-IN      4   133         0           0
46545  2008          67   OTH  WRITE-IN      4   133         0           0
46546  2008          67   OTH  WRITE-IN      5   133         0           0
46547  2008          67   OTH  WRITE-IN      7   133         0           0
46548  2008          67   OTH  WRITE-IN      7   133         0           0
46549  2008          67   OTH  WRITE-IN      0   133         0           0

[46550 rows x 8 columns]

In [12]:
## create new column that is number of voters for any other candidate
# Create a new column called df_08clean.other where the value is the votes if df_08clean.cand equals 
#'NADER', 'BARR', 'WRITE-IN' and 0 if not.
df_08clean['other'] = df_08clean['votes'].where((df_08clean['cand']=='NADER') | (df_08clean['cand']=='BARR') | (df_08clean['cand']=='WRITE-IN'),0)
df_08clean

,year,countycode,party,cand,votes,FIPS,democrat,republican,other
0,2008,1,DEM,OBAMA,154,1,154,0,0
1,2008,1,DEM,OBAMA,167,1,167,0,0
2,2008,1,DEM,OBAMA,97,1,97,0,0
3,2008,1,DEM,OBAMA,360,1,360,0,0
4,2008,1,DEM,OBAMA,178,1,178,0,0
5,2008,1,DEM,OBAMA,333,1,333,0,0
6,2008,1,DEM,OBAMA,377,1,377,0,0
7,2008,1,DEM,OBAMA,453,1,453,0,0
8,2008,1,DEM,OBAMA,356,1,356,0,0
9,2008,1,DEM,OBAMA,547,1,547,0,0
10,2008,1,DEM,OBAMA,636,1,636,0,0
11,2008,1,DEM,OBAMA,426,1,426,0,0
12,2008,1,DEM,OBAMA,319,1,319,0,0
13,2008,1,DEM,OBAMA,536,1,536,0,0
14,2008,1,DEM,OBAMA,246,1,246,0,0
15,2008,1,DEM,OBAMA,284,1,284,0,0
16,2008,1,DEM,OBAMA,130,1,130,0,0
17,2008,1,DEM,OBAMA,441,1,441,0,0
18,2008,1,DEM,OBAMA,380,1,380,0,0
19,2008,1,DEM,OBAMA,175,1,175,0,0
20,2008,1,DEM,OBAMA,364,1,364,0,0
21,2008,1,DEM,OBAMA,540,1,540,0,0
22,2008,1,DEM,OBAMA,953,1,953,0,0
23,2008,1,DEM,OBAMA,478,1,478,0,0
24,2008,1,DEM,OBAMA,408,1,408,0,0
25,2008,1,DEM,OBAMA,382,1,382,0,0
26,2008,1,DEM,OBAMA,197,1,197,0,0
27,2008,1,DEM,OBAMA,305,1,305,0,0
28,2008,1,DEM,OBAMA,409,1,409,0,0
29,2008,1,DEM,OBAMA,253,1,253,0,0
...,...,...,...,...,...,...,...,...,...
46520,2008,67,OTH,WRITE-IN,5,133,0,0,5
46521,2008,67,OTH,WRITE-IN,4,133,0,0,4
46522,2008,67,OTH,WRITE-IN,2,133,0,0,2
46523,2008,67,OTH,WRITE-IN,5,133,0,0,5
46524,2008,67,OTH,WRITE-IN,4,133,0,0,4
46525,2008,67,OTH,WRITE-IN,0,133,0,0,0
46526,2008,67,OTH,WRITE-IN,0,133,0,0,0
46527,2008,67,OTH,WRITE-IN,6,133,0,0,6
46528,2008,67,OTH,WRITE-IN,1,133,0,0,1
46529,2008,67,OTH,WRITE-IN,5,133,0,0,5
46530,2008,67,OTH,WRITE-IN,6,133,0,0,6
46531,2008,67,OTH,WRITE-IN,5,133,0,0,5
46532,2008,67,OTH,WRITE-IN,5,133,0,0,5
46533,2008,67,OTH,WRITE-IN,2,133,0,0,2
46534,2008,67,OTH,WRITE-IN,5,133,0,0,5
46535,2008,67,OTH,WRITE-IN,7,133,0,0,7
46536,2008,67,OTH,WRITE-IN,11,133,0,0,11
46537,2008,67,OTH,WRITE-IN,3,133,0,0,3
46538,2008,67,OTH,WRITE-IN,6,133,0,0,6
46539,2008,67,OTH,WRITE-IN,4,133,0,0,4
46540,2008,67,OTH,WRITE-IN,3,133,0,0,3
46541,2008,67,OTH,WRITE-IN,3,133,0,0,3
46542,2008,67,OTH,WRITE-IN,7,133,0,0,7
46543,2008,67,OTH,WRITE-IN,5,133,0,0,5
46544,2008,67,OTH,WRITE-IN,4,133,0,0,4
46545,2008,67,OTH,WRITE-IN,4,133,0,0,4
46546,2008,67,OTH,WRITE-IN,5,133,0,0,5
46547,2008,67,OTH,WRITE-IN,7,133,0,0,7
46548,2008,67,OTH,WRITE-IN,7,133,0,0,7
46549,2008,67,OTH,WRITE-IN,0,133,0,0,0

In [13]:
#group by FIPS
grp = df_08clean.groupby(['countycode',"FIPS"])

#calculate totals by FIPS of democrat, republican, and other
df_08partyvotes = grp[['democrat','republican','other']].sum()
df_08partyvotes

                 democrat  republican  other
countycode FIPS
1          1        17633       26349    681
2          3       372474      271886   5927
3          5        11138       18542    401
4          7        40499       42895   1638
5          9         6059       16124    325
6          11       97047       80513   2951
7          13       19813       32708    777
8          15       10306       15057    521
9          17      179031      150248   3645
10         19       32260       57074   1427
11         21       32451       31995   1224
12         23         879        1323     55
13         25       13464       12957    629
14         27       41950       32992   1169
15         29      137833      114421   2998
16         31        6746       10737    384
17         33       14555       18662    792
18         35        7097        7504    190
19         37       13191       14447    570
20         39       16780       20750    604
21         41       48306       63739   1780
22         43       69871       58220   1316
23         45      178870      115273   3367
24         47        7290        6676    395
25         49       75775       50351   1565
26         51       25895       25780    605
27         53        1038        1366     64
28         55       21169       41906    566
29         57        1576        4642     88
30         59        7829        7889    258
...                   ...         ...    ...
38         75       23310       34314    939
39         77       87089       63382   2002
40         79       72492       61127   2349
41         81       18381       30280    786
42         83        6465        9224    326
43         85       26411       26565   1192
44         87        5375       10929    198
45         89       39453       28293    697
46         91      253553      165962   3473
47         93        3347        4555     85
48         95       75255       58551   2147
49         97       14328       19015    592
50         99        6396       13058    291
51         101     595980      117221   4824
52         103      11493       12519    273
53         105       2300        5109    174
54         107      28300       33767    990
55         109       5382        9900    197
56         111      12878       21686    804
57         113       1233        1841     57
58         115       8381       10633    369
59         117       6390       11326    268
60         119       7333        9859    283
61         121       9238       13718    525
62         123       8537        9685    441
63         125      46119       50702   1638
64         127       9892       12702    338
65         129      72721      102294   1858
66         131       5985        6949    339
67         133      82839      109268   3166

[67 rows x 3 columns]

In [14]:
list(df_08partyvotes)

['democrat', 'republican', 'other']

In [15]:
# create new column with WGTP30/WGTP to get % renter hhds in poverty
df_08partyvotes['victory_margin'] = ((df_08partyvotes['republican'] - df_08partyvotes['democrat']))/((df_08partyvotes['republican'] + df_08partyvotes['democrat']))
df_08partyvotes.head()

                 democrat  republican  other  victory_margin
countycode FIPS
1          1        17633       26349    681        0.198172
2          3       372474      271886   5927       -0.156105
3          5        11138       18542    401        0.249461
4          7        40499       42895   1638        0.028731
5          9         6059       16124    325        0.453726

In [16]:
# export election results with VICTORY MARGINS by county in PA, 2008
df_08partyvotes.to_csv('electionresults08_PAcounties.csv')